/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consultorio;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.ListaPaciente;
import modelos.Paciente;

/**
 *
 * @author Patrik
 */
public class DetalhesConsulta extends javax.swing.JFrame {

    private ListaPaciente lista;
    private JTable tabelaPacientes;

    /**
     * Creates new form DetalhesConsulta
     *
     * @param lista
     * @param tabelaPacientes
     */
    public DetalhesConsulta(ListaPaciente lista, JTable tabelaPacientes) {
        initComponents();
        this.lista = lista;
        this.tabelaPacientes = tabelaPacientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbConsultaRealizada = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalhes da Consulta");

        jcbConsultaRealizada.setText("Consulta Realizada");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Receita e observações:");

        txtMotivo.setColumns(20);
        txtMotivo.setLineWrap(true);
        txtMotivo.setRows(5);
        jScrollPane1.setViewportView(txtMotivo);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcbConsultaRealizada)
                    .addComponent(jLabel1)
                    .addComponent(btnFinalizar))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcbConsultaRealizada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // Criar um novo objeto Paciente para armazenar os detalhes da consulta
        Paciente consulta = new Paciente();

        // Definir se a consulta foi realizada com base na seleção da JCheckBox
        consulta.setConsultaRealizada(jcbConsultaRealizada.isSelected());

        // Definir as observações da receita na consulta
        consulta.setObservacoes(txtMotivo.getText());

        // Adicionar a consulta à lista de consultas (tabelaPacientes)
        DefaultTableModel model = (DefaultTableModel) tabelaPacientes.getModel();
        model.addRow(new Object[]{
            "", // Nome do paciente, pode ser vazio neste contexto
            "", // CPF do paciente, pode ser vazio neste contexto
            "", // Telefone do paciente, pode ser vazio neste contexto
            "", // Data da consulta, pode ser vazio neste contexto
            consulta.getConsultaRealizada() ? "Sim" : "Não", // Consulta realizada
            consulta.getObservacoes() // Observações da receita
        });

        // Fechar a janela DetalhesConsulta após clicar em "Finalizar"
        dispose();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            // Supondo que você tenha objetos ListaPaciente e JTable disponíveis
            ListaPaciente lista1 = new ListaPaciente();
            JTable tabelaPacientes1 = new JTable();
            new DetalhesConsulta(lista1, tabelaPacientes1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbConsultaRealizada;
    private javax.swing.JTextArea txtMotivo;
    // End of variables declaration//GEN-END:variables

}
