/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consultorio;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.ListaPaciente;
import modelos.Paciente;

/**
 *
 * @author Patrik
 */
public class CadastroConsultaPaciente extends javax.swing.JFrame {

    private JTable tabelaPacientes;

    private ListaPaciente lista;

    /**
     * Creates new form CadastroConsultaPaciente
     *
     * @param lista
     * @param tabelaPacientes
     */
    public CadastroConsultaPaciente(ListaPaciente lista, JTable tabelaPacientes) {
        initComponents();
        this.lista = lista;
        this.tabelaPacientes = tabelaPacientes; // Inicialize a variável
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbisPaciente = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();
        txtTelefone = new javax.swing.JTextField();
        txtNomedoPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jftDataDaConsulta = new javax.swing.JFormattedTextField();
        jftCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbisPaciente.setText("Já é paciente");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Paciente");

        jLabel2.setText("CPF");

        jLabel3.setText("Telefone");

        jLabel4.setText("Data da Consulta");

        try {
            jftDataDaConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cadastrar Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCadastrar)
                        .addComponent(jcbisPaciente)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomedoPaciente)
                                .addComponent(txtTelefone)
                                .addComponent(jftCPF)
                                .addComponent(jftDataDaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(200, 200, 200)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomedoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jftDataDaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(27, 27, 27)
                .addComponent(jcbisPaciente)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Paciente pac = new Paciente();
        // Setar os valores usando os componentes passados como parâmetros
        pac.setNome(txtNomedoPaciente.getText());
        pac.setCpf(jftCPF.getText());
        pac.setTelefone(txtTelefone.getText());
        pac.setData(jftDataDaConsulta.getText());

        // Adiciona o paciente à lista
        lista.adicionar(pac);

        // Atualiza a tabela com as informações do paciente
        DefaultTableModel model = (DefaultTableModel) tabelaPacientes.getModel();
        model.addRow(new Object[]{
            pac.getNome(),
            pac.getCpf(),
            pac.getTelefone(),
            pac.getData(),
        });

        // Passando os argumentos necessários para o construtor DetalhesConsulta
        DetalhesConsulta cad = new DetalhesConsulta(lista, tabelaPacientes);
        cad.setVisible(true);
        dispose(); // Fecha a janela atual após abrir a janela DetalhesConsulta
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ListaPaciente lista = new ListaPaciente();
        java.awt.EventQueue.invokeLater(() -> {
            Consultorio consultorio = new Consultorio(lista);
            consultorio.setVisible(true);
            new CadastroConsultaPaciente(lista, consultorio.getTabelaPacientes()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jcbisPaciente;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftDataDaConsulta;
    private javax.swing.JTextField txtNomedoPaciente;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
